---
title: Batu Projects
timezone: UTC
collections:
  about:
    title: About
    output: false
  home-sections:
    title: Home Sections
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
    layout: project
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    title: ''
    categories:
    - editorial
<<<<<<< HEAD
=======
    position: ''
>>>>>>> a6e1d5c747e1606e576ccfc8d6c9eff56407bf58
    credits: some credit go here
    layout: project
    thumbnail_image: ''
    images:
    - path: ''
      class: ''
    has_video: false
    video_embed: ''
- scope:
    path: ''
    type: home_sections
  values:
    title: Demo Title
    layout: default
    link: ''
    background_image: "/images/home3.jpg"
    is_video: false
    video_url: ''
name: Batu
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
