---
title: Batu Jekyll
timezone: UTC
collections:
  about:
    title: About
    output: false
  clients:
    title: Clients
    output: false
  home-sections:
    title: Home Sections
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
    layout: project
  uploads:
    title: Uploads
    output: true
name: Batu
markdown: redcarpet
highlighter: pygments
exclude:
- node_modules
- gulpfile.js
- package.json
